version: '3.8'

services:
  app:
    image: markolalic/demo-docker:latest  # Replace with your application image
    ports:
      - "8080:8080"  # Maps host port 3000 to container port 3000
    environment:
      - DATABASE_URL=mysql://user:password@db:3306/mydatabase
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql  # Persist database data

volumes:
  db_data:  # Defines a named volume for persistent storage
